### ISSUE TITLE
ssr的时候如果引的是node_modules中的css，好像无效.....是不是我姿势不对

### ISSUE THREAD

**Issue by L-x-C** [Lanfei/webpack-isomorphic#1]
就比如我import './a.css';
这没有问题，生成的webpack.assets.json里是有的

但比如我import 'antd/dist/antd.css'; 
这就不行了...生成的webpack.assets.json里也没有

**Comment by Lanfei** [comment]
@L-x-C 
感谢反馈，问题已修复，请测试~
